name: Build

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

env:
  T4_MAX_TYPE_PARAM: 16

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dotnet tools
      run: dotnet tool restore
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name : Test
      run: dotnet test --no-build -c Release -l "console;verbosity=detailed"
    - name: Pack
      run: dotnet pack --no-build -c Release -o artifacts/
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: nupkg
        path: artifacts/*.nupkg
    - name: NuGet add souce
      run: dotnet nuget add source -u hikarin522 -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text -n "github" "https://nuget.pkg.github.com/hikarin522/index.json"
    - name: Publish
      run: dotnet nuget push "artifacts/*.nupkg" -k ${{ secrets.GITHUB_TOKEN }} -s "github" --skip-duplicate
